puppet_hosts:
  children:
    puppet_master:
    puppet_nodes:
    # non_localhost:

puppet_master:
  hosts:
    puppet1:
      ansible_host: localhost
      ansible_port: 2201

puppet_nodes:
  hosts:
    puppet2:
      ansible_host: localhost
      ansible_port: 2202
    puppet3:
      ansible_host: localhost
      ansible_port: 2203

# non_localhost:
#   hosts:
#     host1.domain.local:
