---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-root
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: local-path
  hostPath:
    path: /tmp/nginx-root

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-conf
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  storageClassName: local-path
  hostPath:
    path: /tmp/nginx-conf
