---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: www
        - mountPath: /etc/nginx/conf.d
          name: conf
  volumes:
    - name: www
      persistentVolumeClaim:
        claimName: nginx-root
    - name: conf
      persistentVolumeClaim:
        claimName: nginx-conf
