import:
  - /LOCAL/Published/configs/alacrittyCommon.yml
font:
  size: 14
  normal:
    family: CascadiaCode
window:
  decorations: none
key_bindings:
  - {key: 58, mods: Shift|Alt, action: ToggleViMode      }
  - {key: 58, mods: None     , chars : "\x1b\x1b\x18\x05"}
  - {key: 58, mods: Shift    , chars : "\x1bp"           }
  - {key: V , mods: Alt      , action: Paste             }
shell:
  program: /LOCAL/Sources/nushell/target/release/nu
