import:
  - /Users/yerlan.sergaziyev/Published/configs/alacrittyCommon.yml
font:
  size: 19
  normal:
    family: Monaco
key_bindings:
  - {key: RWin, mods: Shift|Alt, action: ToggleViMode      }
  - {key: RWin, mods: None     , chars : "\x1b\x1b\x18\x05"}
  - {key: RWin, mods: Shift    , chars : "\x1bp"           }
shell:
  program: /Users/yerlan.sergaziyev/Sources/nushell/target/release/nu
working_directory: /Users/yerlan.sergaziyev/Gerrit
