font:
  size: 14
  normal:
    family: CascadiaCode
    style: Regular
mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  # startup_mode: Fullscreen
  startup_mode: Maximized
key_bindings:
  - { key: 11      , mods: Control, action: none         }  # 0
  - { key: L       , mods: Control, action: none         }  # l
  - { key: 41      , mods: None   , chars : "`"          }
  - { key: 41      , mods: Shift  , chars : "~"          }
  - { key: 13      , mods: None   , chars : "="          }
  - { key: 26      , mods: None   , chars : "["          }
  - { key: 26      , mods: Shift  , chars : "{"          }
  - { key: 26      , mods: Control, chars : "\x1b"       }
  - { key: 27      , mods: None   , chars : "]"          }
  - { key: 27      , mods: Shift  , chars : "}"          }
  - { key: 27      , mods: Control, chars : "\x1d"       }
  - { key: Grave   , mods: None   , chars : "`"          }
  - { key: Grave   , mods: Shift  , chars : "~"          }
  - { key: Equals  , mods: None   , chars : "="          }
  - { key: LBracket, mods: None   , chars : "["          }
  - { key: LBracket, mods: Shift  , chars : "{"          }
  - { key: LBracket, mods: Control, chars : "\x1b"       }
  - { key: RBracket, mods: None   , chars : "]"          }
  - { key: RBracket, mods: Shift  , chars : "}"          }
  - { key: RBracket, mods: Control, chars : "\x1d"       }
  - { key: Back    , mods: Shift  , chars : "\x1b[3~"    }  # bs del
  - { key: Return  , mods: Shift  , chars : "\x1b[13;2u" }  # cr s-ret
  - { key: Space   , mods: Shift  , chars : "\x1b&"      }  # sp a-&
  - { key: LControl, mods: None   , chars : "\x1b"       }  # caps esc
  - { key: LWin    , mods: None   , chars : "\x1b"       }  # caps esc
  - { key: LControl, mods: Shift  , chars : "\x1b-\x1bu" }  # s-caps a-- a-u
  - { key: LWin    , mods: Shift  , chars : "\x1b-\x1bu" }  # s-caps a-- a-u
shell:
  program: /LOCAL/Sources/nushell/target/release/nu
# working_directory: ~
