font:
  size: 14
  normal:
    family: JetBrains Mono
    style: Regular

mouse:
  hide_when_typing: true

scrolling:
  history: 10000

shell:
  program: /home/yerlan/.local/bin/fish

# window:
  # decorations: none

# working_directory: Synced

key_bindings:
  - { key: C, mods: Control , chars: "\x03" }
  - { key: Return, mods: Command , action: ToggleViMode }
  - { key: Return, mods: Shift , chars: "\x1b[13;2u" }
  - { key: Space, mods: Shift , chars: "\x1b" }
