font:
  size: 13
  normal:
    family: JetBrains Mono
    style: Regular
mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  # startup_mode: Fullscreen
  startup_mode: Maximized
key_bindings:
  # - { key: Pause, mods: None, chars: "\x1b[2~" }
  # - { key: Pause, mods: Shift, chars: "\x1b[2;2~" }
  - { key: Back, mods: Shift, chars: "\x1b[3;2~" }
  - { key: Space, mods: Shift, chars: "\x1b\x20" }
  # - { key: F2, mods: None, chars: "\x1b[1;5C" }
  # - { key: F14, mods: None, chars: "\x1b[1;5D" }
  # - { key: 13, mods: None, chars: "=" }
  # - { key: 41, mods: None, chars: "`" }
  # - { key: 41, mods: Shift, chars: "~" }
  # - { key: 26, mods: None, chars: "[" }
  # - { key: 26, mods: Control, chars: "\x1b[5~" }
  # - { key: 26, mods: Shift, chars: "{" }
  # - { key: 27, mods: None, chars: "]" }
  # - { key: 27, mods: Control, chars: "\x1b[6~" }
  # - { key: 27, mods: Shift, chars: "}" }
  # - { key: C, mods: Control, chars: "\x03" }
  # - { key: Grave, mods: None, chars: "`" }
  # - { key: Grave, mods: Shift, chars: "~" }
  # - { key: Equals, mods: None, chars: "=" }
  # - { key: LBracket, mods: None, chars: "[" }
  # - { key: LBracket, mods: Shift, chars: "{" }
  # - { key: RBracket, mods: None, chars: "]" }
  # - { key: RBracket, mods: Shift, chars: "}" }
  # - { key: H, mods: Control|Shift, chars: "\x1b[1;2D"}
  # - { key: J, mods: Control|Shift, chars: "\x1b[1;2B"}
  # - { key: K, mods: Control|Shift, chars: "\x1b[1;2A"}
  # - { key: L, mods: Control|Shift, chars: "\x1b[1;2C"}
# shell:
  # program: /home/yerlan/.local/bin/elvish
# working_directory: Synced
