font:
  size: 13
  normal:
    family: JetBrains Mono
    style: Regular
mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  startup_mode: Maximized
key_bindings:
  - { key: Back, mods: Control, chars: "\x1b[3;6~" }
  - { key: Back, mods: Shift, chars: "\x1b[3;2~" }
  - { key: Return, mods: Control, chars: "\x1b[1;5C" }
  - { key: Return, mods: Shift, chars: "\x1b[1;2C" }
  - { key: Semicolon, mods: Control, chars: "\x1b[1;5F" }
  - { key: Space, mods: Shift, chars: "\x1b\x20" }
  - { key: 13, mods: None, chars: "=" }
  - { key: 41, mods: None, chars: "`" }
  - { key: 41, mods: Shift, chars: "~" }
  - { key: 26, mods: None, chars: "[" }
  - { key: 26, mods: Control, chars: "\x1b[5~" }
  - { key: 26, mods: Shift, chars: "{" }
  - { key: 27, mods: None, chars: "]" }
  - { key: 27, mods: Control, chars: "\x1b[6~" }
  - { key: 27, mods: Shift, chars: "}" }
  # - { key: C, mods: Control, chars: "\x03" }
  # - { key: Grave, mods: None, chars: "`" }
  # - { key: Grave, mods: Shift, chars: "~" }
  # - { key: Equals, mods: None, chars: "=" }
  # - { key: LBracket, mods: None, chars: "[" }
  # - { key: LBracket, mods: Shift, chars: "{" }
  # - { key: RBracket, mods: None, chars: "]" }
  # - { key: RBracket, mods: Shift, chars: "}" }
shell:
  program: /usr/bin/fish
# working_directory: Synced
