font:
  size: 14
  normal:
    family: CascadiaCode
    style: Regular
mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  # startup_mode: Fullscreen
  startup_mode: Maximized
key_bindings:
  - { key: 11      , mods: Control, action: none         }  # 0
  - { key: L       , mods: Control, action: none         }  # l
  - { key: Back    , mods: Shift  , chars : "\x1b[3~"    }  # bs del
  - { key: Return  , mods: Shift  , chars : "\x1b[13;2u" }  # cr s-ret
  - { key: Space   , mods: Shift  , chars : "\x1b&"      }  # sp a-&
  - { key: I       , mods: Control, chars : "\x1b\x02"   }  # i a-c-b
  - { key: M       , mods: Control, chars : "\x1b\x06"   }  # i a-c-f
  - { key: Caret   , mods: None   , chars : "`"          }
  - { key: Caret   , mods: Shift  , chars : "~"          }
shell:
  program: /LOCAL/Sources/nushell/target/release/nu
# working_directory: ~
