mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  startup_mode: Maximized
key_bindings:
  - { key: Back  , mods: Shift, chars : "\x18"  } # Ctrl-x
  - { key: End, mods: None, chars : "\x03"} # Ctrl-c
  - { key: End, mods: Shift, chars : "\x01"} # Ctrl-a
  - { key: Return, mods: Shift, chars : "\x05"} # Ctrl-e
  - { key: Space, mods: Shift, chars : "\x12"} # Ctrl-r
