import:
  - /Users/yerlan.sergaziyev/Published/configs/alacrittyCommon.yml
font:
  size: 19
  normal:
    family: Monaco
shell:
  program: /Users/yerlan.sergaziyev/Sources/nushell/target/release/nu
working_directory: /Users/yerlan.sergaziyev/Projects
