import:
  - ~/Published/configs/alacrittyCommon.yml
font:
  size: 18
  normal:
    family: Monaco
key_bindings:
  - { key: LBracket  , mods: None , chars : "["   }
  - { key: LBracket  , mods: Shift, chars : "{"   }
  - { key: RBracket  , mods: None , chars : "]"   }
  - { key: RBracket  , mods: Shift, chars : "}"   }
  - { key: Grave     , mods: None , chars : "`"   }
  - { key: Grave     , mods: Shift, chars : "~"   }
  - { key: Backslash , mods: None , chars : "\\"  }
  - { key: Backslash , mods: Shift, chars : "|"   }
shell:
  program: /Users/yerlan/.cargo/bin/nu
  args:
    - --config ~/Published/configs/configDark.nu
    - --env-config ~/Published/configs/envDark.nu
