font:
  size: 13
  normal:
    family: JetBrains Mono
    style: Regular

mouse:
  hide_when_typing: true

scrolling:
  history: 10000

shell:
  program: /home/yerlan/.local/bin/fish

window:
  decorations: none
  startup_mode: Maximized

# working_directory: Synced


key_bindings:
  - { key: Back, mods: Control, chars: "\x1b[3;6~" }
  - { key: Back, mods: Shift, chars: "\x1b[3;2~" }
  - { key: Return, mods: Control, chars: "\x1b[1;5F" }
  - { key: Return, mods: Shift, chars: "\x1b[13;2u" }
  - { key: Space, mods: Shift, chars: "\x1b\x20" }
  # - { key: C, mods: Control, chars: "\x03" }
  - { key: 41, mods: None, chars: "`" }
  - { key: 41, mods: Shift, chars: "~" }
  - { key: 13, mods: None, chars: "=" }
  - { key: 26, mods: None, chars: "[" }
  - { key: 26, mods: Shift, chars: "{" }
  - { key: 27, mods: None, chars: "]" }
  - { key: 27, mods: Shift, chars: "}" }
  # - { key: Grave, mods: None, chars: "`" }
  # - { key: Grave, mods: Shift, chars: "~" }
  # - { key: Equals, mods: None, chars: "=" }
  # - { key: LBracket, mods: None, chars: "[" }
  # - { key: LBracket, mods: Shift, chars: "{" }
  # - { key: RBracket, mods: None, chars: "]" }
  # - { key: RBracket, mods: Shift, chars: "}" }
  - { key: 26, mods: Control, chars: "\x1b" }
  - { key: 27, mods: Control, chars: "" }

# Colors (Tomorrow Night)
colors:
  # Default colors
  primary:
    background: '0x1d1f21'
    foreground: '0xc5c8c6'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x1d1f21'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x1d1f21'
    red:     '0xcc6666'
    green:   '0xb5bd68'
    yellow:  '0xe6c547'
    blue:    '0x81a2be'
    magenta: '0xb294bb'
    cyan:    '0x70c0ba'
    white:   '0x373b41'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xff3334'
    green:   '0x9ec400'
    yellow:  '0xf0c674'
    blue:    '0x81a2be'
    magenta: '0xb77ee0'
    cyan:    '0x54ced6'
    white:   '0x282a2e'
