font:
  size: 14
  normal:
    family: JetBrains Mono
    style: Regular

mouse:
  hide_when_typing: true

scrolling:
  history: 10000

# shell:
  # program: /usr/bin/zsh

# window:
  # decorations: none

# working_directory: Synced

key_bindings:
  - { key: Grave, mods: None , chars: “`” }
  - { key: Grave, mods: Shift , chars: “~” }
  - { key: Key3, mods: Shift , chars: “#” }
  - { key: Key4, mods: Shift , chars: “$” }
  - { key: Key5, mods: Shift , chars: “%” }
  - { key: Key6, mods: Shift , chars: “^” }
  - { key: Key7, mods: Shift , chars: “&” }
  - { key: Key8, mods: Shift , chars: “*” }
  - { key: Minus, mods: Shift , chars: “_” }
  - { key: Equals, mods: None , chars: “=” }
  - { key: Equals, mods: Shift , chars: “+” }
  - { key: LBracket, mods: None , chars: “[” }
  - { key: LBracket, mods: Shift , chars: “{” }
  - { key: RBracket, mods: None , chars: “]” }
  - { key: RBracket, mods: Shift , chars: “}” }
  - { key: Backslash, mods: None , chars: “\\” }
  - { key: Backslash, mods: Shift , chars: “|” }
  - { key: Comma, mods: Shift , chars: “<” }
  - { key: Period, mods: Shift , chars: “>” }
  - { key: Return, mods: Alt, action: ToggleViMode }
  - { key: Return, mods: Command, action: ToggleViMode }
  - { key: Return, mods: Shift , chars: “\x1b” }
