font:
  size: 14
  normal:
    family: CascadiaCode
    style: Regular
mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  # startup_mode: Maximized
key_bindings:
  - { key: 58, mods: Shift|Alt, chars  : "set -o vi && clear\r"  }
  - { key: RWin, mods: Shift|Alt, chars  : "set -o vi && clear\r"  }
  - { key: 58      , mods: None   , chars : "\x1b"      }
  - { key: 58      , mods: Shift  , action: ToggleViMode}
  - { key: Back    , mods: Shift  , chars : "\x1b[3~"   }  # del
  - { key: P       , mods: Command, chars : "\x1bp"     }
  - { key: RWin    , mods: None   , chars : "\x1b"      }
  - { key: RWin    , mods: Shift  , action: ToggleViMode}
  - { key: Return  , mods: Shift  , chars : "\x1b[13;2u"}  # s-ret
  - { key: Space   , mods: Shift  , chars : "\x1bg"     }
  - { key: V       , mods: Alt    , action: Paste       }
shell:
  program: /LOCAL/Sources/nushell/target/release/nu
# working_directory: ~
