import:
  - /LOCAL/Published/configs/alacrittyCommon.yml
font:
  size: 14
  normal:
    family: CascadiaCode
window:
  decorations: none
key_bindings:
  - {key: 58, mods: None   , chars: "\x1b"    }
  - {key: 58, mods: Shift  , chars: "\x18\x05"}
  - {key: M , mods: Control, chars: "\x1b[F"  }
shell:
  program: /LOCAL/Sources/nushell/target/release/nu
