font:
  size: 13
  normal:
    family: JetBrains Mono
    style: Regular
mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  # startup_mode: Fullscreen
  startup_mode: Maximized
key_bindings:
  - { key: Back, mods: Shift, chars: "\x1b[3;2~" }
  - { key: Return, mods: Shift, chars: "\x1b[13;2u" }
  - { key: Space, mods: Shift, chars: "\0" }
  # - { key: C, mods: Control, chars: "\x03" }
shell:
  program: /usr/bin/zsh
# working_directory: Synced
