font:
  size: 14
  normal:
    family: JetBrains Mono
    style: Regular

mouse:
  hide_when_typing: true

scrolling:
  history: 10000

# shell:
  # program: /usr/bin/zsh

# window:
  # decorations: none

# working_directory: Synced
key_bindings:
  - { key: Down, mods: None , chars: "\x1b" }
