mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  startup_mode: Maximized
key_bindings:
  # - { key: Return, mods: Shift, chars : "\x1b[13;2u"}
  - { key: Back  , mods: Shift, chars : "\x1b[1;2D"  }
