import:
  - /Users/yerlan.sergaziyev/Published/configs/alacrittyCommon.yml
font:
  size: 19
  normal:
    family: Monaco
window:
  decorations: none
shell:
  program: /Users/yerlan.sergaziyev/Sources/fish-shell/fish
working_directory: /Users/yerlan.sergaziyev/Projects
