import:
  - /Users/yerlan.sergaziyev/Published/configs/alacrittyCommon.yml
font:
  size: 19
  normal:
    family: Monaco
key_bindings:
  - {key: RWin, mods: None , chars : "\x1b"    }
  - {key: RWin, mods: Shift, chars : "\x18\x05"}
shell:
  program: /Users/yerlan.sergaziyev/Sources/nushell/target/release/nu
working_directory: /Users/yerlan.sergaziyev/Gerrit
