import:
  - /LOCAL/Published/configs/alacrittyCommon.yml
font:
  size: 14
  normal:
    family: CascadiaCode
window:
  decorations: none
key_bindings:
  - { key: 58, mods: Shift|Alt, chars  : "set -o vi && clear\r"  }
  - { key: 58      , mods: None   , chars : "\x1b"      }
  - { key: 58      , mods: Shift  , action: ToggleViMode}
  - { key: V       , mods: Alt    , action: Paste       }
shell:
  program: /LOCAL/Sources/nushell/target/release/nu
