import:
  - /LOCAL/Published/configs/alacrittyCommon.yml
font:
  size: 15
  normal:
    family: CascadiaCode
window:
  # decorations: none
  startup_mode: FullScreen
key_bindings:
  - { key: 26  , mods: None, chars : "["  }
  - { key: 26  , mods: Shift, chars : "{"  }
  - { key: 27  , mods: None, chars : "]"  }
  - { key: 27  , mods: Shift, chars : "}"  }
  - { key: 41  , mods: None, chars : "`"  }
  - { key: 41  , mods: Shift, chars : "~"  }
  - { key: 43  , mods: None, chars : "\\"  }
  - { key: 43  , mods: Shift, chars : "|"  }
shell:
  program: /home/yerlan/.cargo/bin/nu 
