font:
  size: 13
  normal:
    family: JetBrains Mono
    style: Regular

mouse:
  hide_when_typing: true

scrolling:
  history: 10000

# shell:
  # program: /home/yerlan/.local/bin/fish

window:
  decorations: none
  startup_mode: Maximized

# working_directory: Synced


key_bindings:
  - { key: C, mods: Control , chars: "\x03" }
  - { key: Back, mods: Shift , chars: "\x1b[3;2~" }
  - { key: Return, mods: Command , action: ToggleViMode }
  - { key: Return, mods: Control, action: ToggleViMode }
  - { key: Return, mods: Shift , chars: "\x1b" }
  - { key: Space, mods: Shift , chars: "\x1b\x20" }
  - { key: 41, mods: None , chars: "`" }
  - { key: 41, mods: Shift , chars: "~" }
  - { key: 13, mods: None , chars: "=" }
  - { key: 26, mods: None , chars: "[" }
  - { key: 26, mods: Shift , chars: "{" }
  - { key: 27, mods: None , chars: "]" }
  - { key: 27, mods: Shift , chars: "}" }
