mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: None
  startup_mode: Maximized
key_bindings:
  - { key: Back  , mods: Shift, chars : "\x1bb"  } # Alt-b
  - { key: End, mods: None, chars : "\x1b"} # Esc
  - { key: End, mods: Shift, chars : "\x1b_"} # Alt-_
  - { key: Return, mods: Shift, chars : "\x1bf"} # Alt-f
  - { key: Space, mods: Shift, chars : "\x1b\x05"} # Alt-Ctrl-e
