quit_on_last_cancel = true

[[verbs]]
invocation = "edit"
key = "enter"
external = "$EDITOR {file}"
leave_broot = false
apply_to = "file"

[[verbs]]
invocation = "cd"
key = "alt-f"
internal = ":print_relative_path"

[[verbs]]
key = "tab"
internal = ":line_down"

[[verbs]]
key = "backtab"
internal = ":line_up"
