theme = 'catppuccin_mocha'
[editor]
auto-format = false
color-modes = true
cursorline = true
line-number = "relative"

[editor.smart-tab]
enable = false
supersede-menu = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.statusline]
center = [ "version-control", "spacer", "total-line-numbers", "spacer", "file-type" ]

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"A-minus" = "no_op"
"A-l" = [ "move_prev_word_start", "collapse_selection", "switch_to_uppercase", "move_next_word_end", "move_char_right" ] # C-S-tab
"A-u" = [ "extend_prev_word_start", "switch_to_uppercase", "ensure_selections_forward", "collapse_selection" ] # C-tab
"C-d" = [ ":insert-output date '+%c'", "goto_line_end_newline" ]
"S-end" = "goto_line_end_newline" # Caps-S-ret
"S-pageup" = [ "move_prev_word_start", "delete_selection", ":insert-output printf '%s' '<></>'", "collapse_selection", "paste_before", "move_prev_word_start", "move_prev_word_start", "collapse_selection", "paste_after", "move_next_word_end", "move_char_right" ] # Caps-S-tab
"C-space" = [ "normal_mode", ":insert-output printf ' '", "move_prev_word_start", ":insert-output printf ' '", "move_next_word_start", "move_char_right", "insert_mode" ]
"esc" = "insert_newline"
"ret" = "normal_mode"

[keys.normal]
"A-l" = "switch_to_lowercase"
"A-u" = "switch_to_uppercase"
"A-backspace" = "remove_primary_selection" # S-backspace
"backspace" = "keep_primary_selection"
"esc" = [ "split_selection_on_newline", "extend_to_line_bounds" ]
"ret" = [ "collapse_selection", "keep_primary_selection" ]
"space" = "collapse_selection"
"tab" = "buffer_picker"
"S-tab" = "file_picker_in_current_directory"
"`" = "jumplist_picker"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = "extend_to_first_nonwhitespace"
"*" = [ "move_char_right", "extend_prev_word_start", "collapse_selection", "extend_next_word_end", "search_selection" ]
"minus" = "surround_delete"
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = [ "select_mode", "repeat_last_motion", "normal_mode" ]
"'" = "surround_add"
"\\" = "surround_replace"
"b" = "extend_prev_word_start"
"B" = "extend_prev_long_word_start"
"d" = [ "hover", "expand_selection" ]
"D" = "extend_search_next"
"e" = "extend_next_word_end"
"E" = "extend_next_long_word_end"
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"J" = [ "extend_line_down", "extend_to_line_bounds" ]
"K" = [ "extend_line_up", "extend_to_line_bounds" ]
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = "redo"
"U" = "extend_search_prev"
"V" = "extend_to_line_bounds"
"w" = "extend_next_word_start"
"W" = "extend_next_long_word_start"
"x" = "delete_selection"
"X" = "delete_selection_noyank"
"Y" = "yank_joined_to_clipboard"
"Z" = "select_all"

[keys.normal.","]
"," = "command_palette"
"/" = "global_search"
"a" = "code_action"
"d" = "diagnostics_picker"
"D" = "workspace_diagnostics_picker"
"f" = ":format"
"h" = "select_references_to_symbol_under_cursor"
"k" = "hover"
"r" = "rename_symbol"
"s" = "symbol_picker"
"S" = "workspace_symbol_picker"
"w" = "make_search_word_bounded"
"y" = "yank_main_selection_to_clipboard"

[keys.normal.g]
"g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ]

[keys.normal.v]
";" = "ensure_selections_forward"
"space" = "trim_selections"
"a" = "select_textobject_around"
"i" = "select_textobject_inner"
"J" = "join_selections_space"
"k" = "shrink_selection"
"m" = "merge_selections"
"M" = "merge_consecutive_selections"
"o" = "flip_selections"
"s" = "keep_selections"
"S" = "remove_selections"
"u" = "switch_to_lowercase"
