theme = 'catppuccin_mocha'
[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
center = [ "version-control", "spacer", "total-line-numbers", "spacer", "file-type" ]

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"A-end" = "goto_line_end_newline" # Caps-S-enter
"A-pageup" = [ "move_prev_word_start", "collapse_selection", "yank", "move_char_right", "paste_after", "move_char_left", "match_brackets", "move_next_word_end", "flip_selections", "extend_char_left", "yank", "match_brackets", "move_char_right", "paste_after", "delete_selection", "paste_after" ] # Caps-S-tab
"A-right" = "move_char_right" # Caps-enter
"C-space" = [ "normal_mode", ":insert-output printf ' '", "move_prev_word_start", ":insert-output printf ' '", "move_next_word_start", "move_char_right", "insert_mode" ]
"C-d" = [ ":insert-output date '+%c'", "goto_line_end_newline" ]
"C-t" = [ "normal_mode", "extend_prev_word_start", ":pipe htmltag", "extend_next_word_start", "extend_next_word_start", "move_char_left", "insert_mode" ]

[keys.normal]
"A-end" = "symbol_picker" # Caps-S-enter
"backspace" = "keep_primary_selection"
"C-S-del" = "remove_primary_selection" # S-backspace
"ret" = [ "split_selection_on_newline", "extend_to_line_bounds" ]
"space" = "collapse_selection"
"tab" = "buffer_picker"
"S-tab" = "file_picker_in_current_directory"
"`" = "jumplist_picker"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = [ "select_mode", "goto_first_nonwhitespace", "normal_mode" ]
"*" = [ "extend_next_word_start", "flip_selections", "extend_prev_word_start", "trim_selections", "search_selection" ]
"minus" = "surround_delete"
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = "repeat_last_motion"
"'" = "surround_add"
"," = { "," = "command_palette", "/" = "global_search", "a" = "code_action", "f" = "select_references_to_symbol_under_cursor", "r" = "rename_symbol", "y" = "yank_joined_to_clipboard", "Y" = "yank_main_selection_to_clipboard" }
"\\" = "surround_replace"
"b" = "extend_prev_word_start"
"B" = "extend_prev_long_word_start"
"C" = [ "extend_to_line_end", "change_selection" ]
"d" = [ "hover", "expand_selection" ]
"D" = [ "extend_to_line_end", "delete_selection" ]
"e" = "extend_next_word_end"
"E" = "extend_next_long_word_end"
"g" = { "g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ] }
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"J" = [ "extend_line_down", "extend_to_line_bounds" ]
"K" = [ "extend_line_up", "extend_to_line_bounds" ]
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = "redo"
"U" = [ "switch_to_uppercase", "ensure_selections_forward", "collapse_selection", "move_char_right" ]
"v" = { "v" = "select_all", "a" = "select_textobject_around", "i" = "select_textobject_inner", "s" = "keep_selections", "S" = "remove_selections", "o" = "flip_selections", ";" = "ensure_selections_forward", "m" = "merge_consecutive_selections", "n" = "shrink_selection", "space" = "trim_selections", "J" = "join_selections_space", "u" = "switch_to_lowercase" }
"V" = "extend_to_line_bounds"
"w" = "extend_next_word_start"
"W" = "extend_next_long_word_start"
"x" = "delete_selection"
"X" = "delete_selection_noyank"
"Y" = [ "extend_to_line_end", "yank" ]
"Z" = "copy_selection_on_next_line"
