theme = "dracula"

[keys.insert]
"A-&" = "no_op" # S-space
"ret" = "normal_mode"
"S-ret" = "insert_newline"

[keys.normal]
"A-&" = "remove_primary_selection" # S-space
"A-C-b" = "jump_forward" # C-i
"C-r" = "redo"
"@" = "replay_macro"
"$" = "extend_to_line_end"
"percent" = "match_brackets"
"^" = [ "select_mode", "goto_first_nonwhitespace", "normal_mode" ]
"+" = "expand_selection"
"'" = "select_all"
"semicolon" = "repeat_last_motion"
"ret" = "collapse_selection"
"S-ret" = "split_selection_on_newline"
"S-tab" = "ensure_selections_forward"
"tab" = "flip_selections"

"D" = "switch_to_lowercase"
"G" = "goto_file_end"
"H" = "rotate_selection_contents_backward"
"M" = "toggle_comments"
"L" = "rotate_selection_contents_forward"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"U" = "switch_to_uppercase"
"V" = "extend_to_line_bounds"
"X" = "remove_selections"

[keys.select]
"A-&" = [ "normal_mode", "remove_primary_selection" ] # S-BS
"A-C-b" = "jump_forward" # C-i
"C-r" = "redo"
"@" = [ "normal_mode", "replay_macro" ]
"$" = "goto_line_end"
"percent" = "match_brackets"
"^" = "goto_first_nonwhitespace"
"+" = [ "normal_mode", "expand_selection" ]
"'" = [ "normal_mode", "select_all" ]
"semicolon" = "repeat_last_motion"
"ret" = [ "normal_mode", "collapse_selection" ]
"S-ret" = [ "normal_mode", "split_selection_on_newline" ]
"S-tab" = "ensure_selections_forward"
"tab" = "flip_selections"

"a" = [ "normal_mode", "select_textobject_around" ]
"D" = [ "normal_mode", "switch_to_lowercase" ]
"G" = [ "goto_file_end", "normal_mode" ]
"H" = [ "normal_mode", "rotate_selection_contents_backward" ]
"i" = [ "normal_mode", "select_textobject_inner" ]
"M" = [ "normal_mode", "toggle_comments" ]
"L" = [ "normal_mode", "rotate_selection_contents_forward" ]
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"U" = [ "normal_mode", "switch_to_uppercase" ]
"V" = [ "normal_mode", "extend_to_line_bounds" ]
"X" = [ "normal_mode", "remove_selections" ]
