theme = 'catppuccin_mocha'

[editor]
auto-format = false
color-modes = true
cursorline = true
line-number = "relative"

[editor.smart-tab]
enable = false
supersede-menu = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.statusline]
center = [ "version-control", "spacer", "total-line-numbers", "spacer", "file-type" ]

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-e" = "goto_line_end_newline"
"C-f" = "move_char_right"
"C-h" = [ "move_prev_word_start", "delete_selection", ":insert-output printf '%s' '<></>'", "collapse_selection", "paste_before", "move_prev_word_start", "move_prev_word_start", "collapse_selection", "paste_after", "move_next_word_end", "move_char_right" ] # HTML tag from word
"C-l" = [ "move_prev_word_start", "collapse_selection", "switch_to_uppercase", "move_next_word_end", "move_char_right" ] # Capitalize word
"C-t" = [ ":insert-output date '+%c'", "goto_line_end_newline" ]
"C-u" = [ "extend_prev_word_start", "switch_to_uppercase", "ensure_selections_forward", "collapse_selection" ] # Uppercase word
"C-space" = [ "normal_mode", ":insert-output printf ' '", "move_prev_word_start", ":insert-output printf ' '", "move_next_word_start", "move_char_right", "insert_mode" ]

[keys.normal]
"C-l" = "switch_to_lowercase"
"C-u" = "switch_to_uppercase"
"A-backspace" = "remove_primary_selection" # C-backspace
"backspace" = "keep_primary_selection"
"C-h" = [ "split_selection_on_newline", "extend_to_line_bounds" ]
"ret" = [ "collapse_selection", "keep_primary_selection" ]
"tab" = "buffer_picker"
"S-tab" = "file_picker_in_current_directory"
"`" = "jumplist_picker"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = "extend_to_first_nonwhitespace"
"*" = [ "move_char_right", "extend_prev_word_start", "collapse_selection", "extend_next_word_end", "search_selection" ]
"minus" = "surround_delete"
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = [ "select_mode", "repeat_last_motion", "normal_mode" ]
"'" = "surround_add"
"\\" = "surround_replace"
"b" = "extend_prev_word_start"
"B" = "extend_prev_long_word_start"
"d" = [ "hover", "expand_selection" ]
"D" = "extend_search_next"
"e" = "extend_next_word_end"
"E" = "extend_next_long_word_end"
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"J" = [ "extend_line_down", "extend_to_line_bounds" ]
"K" = [ "extend_line_up", "extend_to_line_bounds" ]
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = "redo"
"U" = "extend_search_prev"
"v" = "select_mode"
"V" = "extend_to_line_bounds"
"w" = "extend_next_word_start"
"W" = "extend_next_long_word_start"
"x" = "delete_selection"
"X" = "delete_selection_noyank"
"Y" = "yank_joined_to_clipboard"
"Z" = "select_all"


"а" = "append_mode"
"А" = "insert_at_line_end"
"б" = "extend_prev_word_start"
"Б" = "extend_prev_long_word_start"
"в" = "select_mode"
"В" = "extend_to_line_bounds"
"г" = "no_op"
"Г" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"д" = [ "hover", "expand_selection" ]
"Д" = "extend_search_next"
"е" = "extend_next_word_end"
"Е" = "extend_next_long_word_end"
"ж" = "move_visual_line_down"
"Ж" = [ "extend_line_down", "extend_to_line_bounds" ]
"з" = "no_op"
"З" = "select_all"
"и" = "insert_mode"
"И" = "insert_at_line_start"
"й" = "search"
"к" = "move_visual_line_up"
"К" = [ "extend_line_up", "extend_to_line_bounds" ]
"л" = "move_char_right"
"Л" = "extend_char_right"
"м" = "save_selection"
"М" = "toggle_comments"
"н" = "search_next"
"Н" = "search_prev"
"о" = "open_below"
"О" = "open_above"
"п" = "paste_after"
"П" = "paste_before"
"р" = "replace"
"Р" = "replace_with_yanked"
"с" = "select_regex"
"С" = "split_selection"
"т" = "find_till_char"
"Т" = "till_prev_char"
"у" = "undo"
"У" = "extend_search_prev"
"ф" = "find_next_char"
"Ф" = "find_prev_char"
"х" = "move_char_left"
"Х" = "extend_char_left"
"ц" = "change_selection"
"Ц" = "copy_selection_on_next_line"
"ч" = "delete_selection"
"Ч" = "delete_selection_noyank"
"ш" = "no_op"
"Ш" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"щ" = "no_op"
"Щ" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
"ъ" = "format_selections"
"ы" = "yank"
"Ы" = "yank_joined_to_clipboard"
"ь" = "surround_add"
"э" = "surround_replace"
"Э" = "shell_pipe"
"ю" = "extend_next_word_start"
"Ю" = "extend_next_long_word_start"
"я" = "record_macro"
"Я" = "copy_selection_on_prev_line"
"і" = "jumplist_picker"
"І" = "switch_case"

[keys.normal.","]
"space" = "collapse_selection"
";" = "ensure_selections_forward"
"a" = "select_textobject_around"
"d" = "make_search_word_bounded"
"f" = ":format"
"i" = "select_textobject_inner"
"J" = "join_selections_space"
"k" = "shrink_selection"
"m" = "merge_selections"
"M" = "merge_consecutive_selections"
"o" = "flip_selections"
"q" = ":quit"
"Q" = ":quit!"
"s" = "keep_selections"
"S" = "remove_selections"
"t" = "trim_selections"
"u" = "switch_to_lowercase"
"w" = ":write"
"Я" = ":quit!"
"ю" = ":write"
"я" = ":quit"

[keys.normal.g]
"g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ]

# [keys.normal.v]
