theme = "monokai_pro_spectrum"

[keys.insert]
"C-c" = "normal_mode" # END (CAPS)
"tab" = { "l" = "move_char_right", "tab" = "insert_tab", "u" = [ "normal_mode", "move_char_left", "extend_prev_word_start", "switch_to_uppercase", "flip_selections", "move_char_right", "insert_mode" ] }

[keys.normal]
"`" = "jump_backward"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = [ "select_mode", "goto_first_nonwhitespace", "normal_mode" ]
"*" = [ "extend_next_word_start", "flip_selections", "extend_prev_word_start", "trim_selections", "search_selection" ]
"minus" = { "k" = "hover", "l" = "rename_symbol", "a" = "code_action", "s" = "symbol_picker", "S" = "workspace_symbol_picker" }
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = "repeat_last_motion"
"," = { "_" = "trim_selections", "," = "flip_selections", "." = "ensure_selections_forward", "b" = "earlier", "f" = "later", "r" = "redo", "s" = "split_selection_on_newline" }
"'" = { "s" = "surround_add", "r" = "surround_replace", "d" = "surround_delete" }
# "C-a" = "" # S-CAPS (S-END)
"B" = "extend_prev_long_word_start"
"D" = "switch_to_lowercase"
"E" = "extend_next_long_word_end"
"C-e" = [ "extend_line_down", "extend_to_line_bounds" ] # C-CR
"g" = { "g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ] }
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"L" = "extend_char_right"
"m" = "save_selection"
"M" = { "a" = "code_action", "k" = "hover", "r" = "rename_symbol", "s" = "symbol_picker", "w" = "workspace_symbol_picker" }
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = [ "extend_line_up", "extend_to_line_bounds" ] # S-SP
"U" = "switch_to_uppercase"
"v" = { "a" = "select_textobject_around", "i" = "select_textobject_inner", "v" = "select_mode", "ret" = "select_all" }
"V" = "extend_to_line_bounds"
"W" = "extend_next_long_word_start"
"x" = "delete_selection_noyank"
"C-x" = "remove_primary_selection" # S-BS
"X" = "remove_selections"
"backspace" = "keep_primary_selection"
"ret" = { "b" = "buffer_picker", "c" = "yank_joined_to_clipboard", "d" = "file_picker_in_current_directory", "f" = "file_picker", "r" = "replace_selections_with_clipboard", "v" = "paste_clipboard_before", "space" = "command_palette" }
"space" = "collapse_selection"

[keys.select]
