theme = "onedark"

[keys.insert]
"A-minus" = { "A-u" = [ "normal_mode", "extend_prev_word_start", "switch_to_uppercase", "flip_selections", "collapse_selection", "insert_mode" ] }

[keys.normal]
"A-minus" = { "A-u" = "switch_to_uppercase" }
"C-r" = "redo"
"@" = "replay_macro"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"percent" = "match_brackets"
"semicolon" = "repeat_last_motion"
"backspace" = "keep_primary_selection"
"del" = "remove_primary_selection" # S-BS
"ret" = "collapse_selection"
"S-ret" = "add_newline_above"

"G" = "goto_file_end"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"V" = "extend_to_line_bounds"
"x" = "flip_selections"
"X" = "split_selection_on_newline"
"H" = "rotate_selection_contents_backward"
"L" = "rotate_selection_contents_forward"
"+" = "expand_selection"
"'" = "select_all"

[keys.select]
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"ret" = [ "normal_mode", "collapse_selection" ]
"backspace" = [ "normal_mode", "keep_primary_selection" ]
"V" = [ "normal_mode", "extend_to_line_bounds" ]
"x" = "flip_selections"
"X" = [ "normal_mode", "split_selection_on_newline" ]
