[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.statusline]
right = [ "version-control", "spacer", "separator", "diagnostics", "selections", "position", "file-encoding"]

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"home" = "move_char_right" # S-backspace
"pagedown" = "insert_newline" # S-ret
"pageup" = [ ":insert-output printf %s ' '", "move_char_right" ] # S-space
"C-space" = [ "normal_mode", ":insert-output printf ' '", "move_prev_word_start", ":insert-output printf ' '", "move_next_word_start", "move_char_right", "insert_mode" ]
"C-t" = [ "normal_mode", "extend_prev_word_start", ":pipe htmltag", "extend_next_word_start", "extend_next_word_start", "move_char_left", "insert_mode" ]
"C-d" = [ ":insert-output date '+%c'", "goto_line_end_newline" ]

[keys.normal]
"end" = "symbol_picker" # S-esc
"backspace" = "keep_primary_selection"
"home" = "remove_primary_selection" # S-backspace
"ret" = [ "split_selection_on_newline", "extend_to_line_bounds" ]
# "pagedown" = "" # S-ret
"space" = [ "collapse_selection", "hover" ]
# "pageup" = "" # S-space
"tab" = "buffer_picker"
"S-tab" = "file_picker_in_current_directory"
"`" = "jumplist_picker"
"~" = { "~" = "switch_case", "`" = "switch_to_lowercase" }
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = [ "select_mode", "goto_first_nonwhitespace", "normal_mode" ]
"*" = [ "extend_next_word_start", "flip_selections", "extend_prev_word_start", "trim_selections", "search_selection" ]
"minus" = "surround_delete"
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = "repeat_last_motion"
"'" = "surround_add"
"," = { "," = "command_palette", "/" = "global_search", "a" = "code_action", "f" = "select_references_to_symbol_under_cursor", "j" = "join_selections_space", "r" = "rename_symbol" }
"\\" = "surround_replace"
"B" = "extend_prev_long_word_start"
"C" = [ "extend_to_line_end", "change_selection" ]
"d" = "expand_selection"
"D" = [ "extend_to_line_end", "delete_selection" ]
"E" = "extend_next_word_end"
"g" = { "g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ] }
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"J" = [ "extend_line_down", "extend_to_line_bounds" ]
"K" = [ "extend_line_up", "extend_to_line_bounds" ]
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = "redo"
"U" = [ "switch_to_uppercase", "ensure_selections_forward", "collapse_selection", "move_char_right" ]
"v" = { "v" = "select_all", "a" = "select_textobject_around", "i" = "select_textobject_inner", "k" = "keep_selections", "l" = "remove_selections", "o" = "flip_selections", ";" = "ensure_selections_forward", "m" = "merge_consecutive_selections", "n" = "shrink_selection", "space" = "trim_selections" }
"V" = "extend_to_line_bounds"
"W" = "extend_next_long_word_start"
"x" = "delete_selection"
"X" = "delete_selection_noyank"
"Y" = [ "extend_to_line_end", "yank" ]
"Z" = "copy_selection_on_next_line"
