theme = "catppuccin_macchiato"
[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.indent-guides]
render = true

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"A-^" = [ ":insert-output printf %s ' '", "move_char_right" ] # S-SP
"A-_" = [ "normal_mode", "extend_prev_word_start", ":pipe htmltag", "extend_next_word_start", "extend_next_word_start", "move_char_left", "insert_mode" ] # S-CAPS
"A-b" = "delete_char_forward" # S-BS
"A-f" = [ "normal_mode", "move_char_left", "extend_prev_word_start", "switch_to_uppercase", "flip_selections", "move_char_right", "insert_mode" ] # S-CR
"C-d" = ":insert-output date '+%c'"
"C-e" = "goto_line_end_newline"
"C-f" = "move_char_right"
"C-s" = [ "normal_mode", ":update" ]
"C-t" = ":insert-output date '+%T'"
"C-v" = "paste_clipboard_before"
"C-space" = [ "normal_mode", ":insert-output printf ' '", "move_prev_word_start", ":insert-output printf ' '", "move_next_word_start", "move_char_right", "insert_mode" ]

[keys.normal]
"A-^" = "trim_selections" # S-SP
"A-_" = "ensure_selections_forward" # S-CAPS
"S-tab" = "flip_selections"
"tab" = "buffer_picker"
"backspace" = "keep_primary_selection"
"A-b" = "remove_primary_selection" # S-BS
"ret" = "collapse_selection"
"A-f" = "split_selection_on_newline" # S-CR
"`" = "jump_backward"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
# "$" = "ensure_selections_forward"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = [ "select_mode", "goto_first_nonwhitespace", "normal_mode" ]
"*" = [ "extend_next_word_start", "flip_selections", "extend_prev_word_start", "trim_selections", "search_selection" ]
"minus" = "surround_delete"
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = "repeat_last_motion"
"'" = "surround_add"
"," = { "." = ":set line-number absolute", "," = ":set line-number relative", "r" = "later", "u" = "earlier" }
"\\" = "surround_replace"
"B" = "extend_prev_long_word_start"
"C-c" = "yank_main_selection_to_clipboard"
"D" = [ "extend_to_line_bounds", "delete_selection" ]
"E" = "extend_next_long_word_end"
"g" = { "g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ], "j" = "join_selections_space", "u" = "switch_to_lowercase" }
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"J" = [ "extend_line_down", "extend_to_line_bounds" ]
"K" = [ "extend_line_up", "extend_to_line_bounds" ]
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"C-o" = "file_picker_in_current_directory"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = "redo"
"C-s" = ":update"
"U" = "switch_to_uppercase"
"v" = { "a" = "select_textobject_around", "A" = "select_all", "i" = "select_textobject_inner", "v" = "select_mode" }
"V" = "extend_to_line_bounds"
"C-v" = "paste_clipboard_before"
"W" = "extend_next_long_word_start"
"x" = "delete_selection_noyank"
"X" = "remove_selections"
"Y" = [ "extend_to_line_bounds", "yank" ]
"Z" = "keep_selections"
