theme = "monokai_pro_spectrum"

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-c" = "normal_mode" # END (CAPS)
"C-x" = "no_op" # S-SP
"tab" = { "l" = "move_char_right", "tab" = "insert_tab", "u" = [ "normal_mode", "move_char_left", "extend_prev_word_start", "switch_to_uppercase", "flip_selections", "move_char_right", "insert_mode" ] }

[keys.normal]
"`" = "jump_backward"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = [ "select_mode", "goto_first_nonwhitespace", "normal_mode" ]
"*" = [ "extend_next_word_start", "flip_selections", "extend_prev_word_start", "trim_selections", "search_selection" ]
"minus" = [ "extend_line_up", "extend_to_line_bounds", ":set line-number absolute" ]
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = "repeat_last_motion"
"," = { "a" = ":set line-number absolute", "c" = "yank_joined_to_clipboard", "d" = "file_picker_in_current_directory", "e" = "earlier", "f" = "file_picker", "l" = "later", "r" = "replace_selections_with_clipboard", "v" = "paste_clipboard_before", "y" = "redo", "space" = "command_palette" }
"'" = { "s" = "surround_add", "r" = "surround_replace", "d" = "surround_delete" }
"C-a" = "rotate_view" # S-CAPS (S-END)
"B" = "extend_prev_long_word_start"
"C-c" = ":set line-number relative" # END (CAPS)
"D" = "switch_to_lowercase"
"E" = "extend_next_long_word_end"
# "C-e" = "" # S-CR
"g" = { "g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ] }
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"C-r" = "remove_primary_selection" # S-BS
"U" = "switch_to_uppercase"
"v" = { ";" = "ensure_selections_forward", "a" = "select_textobject_around", "i" = "select_textobject_inner", "l" = "flip_selections", "v" = "select_mode", "backspace" = "trim_selections", "ret" = "split_selection_on_newline", "space" = "select_all" }
"V" = "extend_to_line_bounds"
"W" = "extend_next_long_word_start"
"x" = "delete_selection_noyank"
"C-x" = { "a" = "code_action", "k" = "hover", "r" = "rename_symbol", "s" = "symbol_picker", "w" = "workspace_symbol_picker" } # S-SP
"X" = "remove_selections"
"backspace" = "keep_primary_selection"
"ret" = [ "extend_line_down", "extend_to_line_bounds", ":set line-number absolute" ]
"S-tab" = "buffer_picker"
"space" = "collapse_selection"

[keys.select]
