theme = 'catppuccin_latte'

[editor]
auto-format = false
color-modes = true
cursorline = true
line-number = "relative"

[editor.smart-tab]
enable = false
supersede-menu = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.statusline]
center = [ "version-control", "spacer", "total-line-numbers", "spacer", "file-type" ]

[editor.whitespace.render]
tab = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-h" = [ "move_prev_word_start", "delete_selection", ":insert-output printf '%s' '<></>'", "collapse_selection", "paste_before", "move_prev_word_start", "move_prev_word_start", "collapse_selection", "paste_after", "move_next_word_end", "move_char_right" ] # HTML tag from word
"C-l" = [ "move_prev_word_start", "collapse_selection", "switch_to_uppercase", "move_next_word_end", "move_char_right" ] # Capitalize word
"C-t" = [ ":insert-output date '+%c'", "goto_line_end_newline" ]
"C-u" = [ "extend_prev_word_start", "switch_to_uppercase", "ensure_selections_forward", "collapse_selection" ] # Uppercase word
"C-space" = [ "normal_mode", ":insert-output printf ' '", "move_prev_word_start", ":insert-output printf ' '", "move_next_word_start", "move_char_right", "insert_mode" ]

[keys.normal]
"C-b" = "extend_search_prev"
"C-f" = "extend_search_next"
"C-j" = "extend_line_down"
"C-k" = "extend_line_up"
"C-l" = [ "split_selection_on_newline", "extend_to_line_bounds" ]
"C-n" = [ "extend_line_down", "extend_to_line_bounds" ]
"C-o" = "switch_to_lowercase"
"C-p" = [ "extend_line_up", "extend_to_line_bounds" ]
"C-r" = "redo"
"C-u" = [ "extend_prev_word_start", "ensure_selections_forward", "extend_next_word_end", "switch_to_uppercase", "collapse_selection" ] # Uppercase word
"A-backspace" = "remove_primary_selection" # C-backspace
"backspace" = "keep_primary_selection"
"del" = "remove_primary_selection" # S-backspace
"ret" = "collapse_selection"
"tab" = "buffer_picker"
"S-tab" = "file_picker_in_current_directory"
"`" = "jumplist_picker"
"~" = "switch_case"
"@" = "replay_macro"
"#" = "search_selection"
"$" = "extend_to_line_end"
"%" = [ "select_mode", "match_brackets", "normal_mode" ]
"^" = "extend_to_first_nonwhitespace"
"*" = [ "move_char_right", "extend_prev_word_start", "collapse_selection", "extend_next_word_end", "search_selection" ]
"minus" = "surround_delete"
"_" = "rotate_selection_contents_backward"
"+" = "rotate_selection_contents_forward"
"{" = [ "select_mode", "goto_prev_paragraph", "normal_mode", "extend_to_line_bounds" ]
"}" = [ "select_mode", "goto_next_paragraph", "normal_mode", "extend_to_line_bounds" ]
";" = [ "select_mode", "repeat_last_motion", "normal_mode" ]
"'" = "surround_add"
"\\" = "surround_replace"
"b" = "extend_prev_word_start"
"B" = "extend_prev_long_word_start"
"d" = [ "hover", "expand_selection" ]
"D" = "remove_selections"
"e" = "extend_next_word_end"
"E" = "extend_next_long_word_end"
"G" = [ "select_mode", "goto_file_end", "normal_mode", "extend_to_line_bounds" ]
"H" = "extend_char_left"
"L" = "extend_char_right"
"m" = "save_selection"
"M" = "toggle_comments"
"q" = "record_macro"
"Q" = "copy_selection_on_prev_line"
"U" = "switch_to_uppercase"
"v" = "select_mode"
"V" = "extend_to_line_bounds"
"w" = "extend_next_word_start"
"W" = "extend_next_long_word_start"
"x" = "delete_selection"
"X" = "delete_selection_noyank"
"Y" = "yank_joined_to_clipboard"
"Z" = "select_all"

[keys.normal.","]
"space" = "collapse_selection"
";" = "ensure_selections_forward"
"a" = "select_textobject_around"
"d" = "make_search_word_bounded"
"f" = ":format"
"i" = "select_textobject_inner"
"k" = "shrink_selection"
"m" = "merge_selections"
"M" = "merge_consecutive_selections"
"o" = "flip_selections"
"q" = ":quit"
"Q" = ":quit!"
"t" = "trim_selections"
"u" = "switch_to_lowercase"
"w" = ":write"

[keys.normal.g]
"g" = [ "select_mode", "goto_file_start", "normal_mode", "extend_to_line_bounds" ]

# [keys.normal.v]
