add-highlighter global/ number-lines

hook global InsertChar \' %{ exec \'<left> }
hook global InsertChar \" %{ exec \"<left> }
hook global InsertChar ` %{ exec `<left> }
hook global InsertChar \( %{ exec )<left> }
hook global InsertChar \[ %{ exec ]<left> }
hook global InsertChar \{ %[ exec }<left> ]

hook global NormalKey 0 'switch-number-line -relative'
hook global NormalKey \D.* 'switch-number-line'

hook global WinSetOption filetype=html %{
  map buffer normal '<c-_>' '<a-x>: comment-block<ret>' -docstring 'comment/uncomment block'
  map buffer insert '<c-space>' '<esc><a-b>"x\c<lt><c-r>x<gt><lt>/<c-r>x<gt><esc><a-f><lt>;i' -docstring 'add block'
}
hook global WinSetOption filetype=python %{
  map buffer insert '<s-ret>' '<ret>' -docstring 'simple return'
  set-option buffer indentwidth 4
  set-option buffer tabstop 4
}

define-command -hidden extend-next-hump %{ execute-keys '?[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>' }
define-command -hidden extend-previous-hump %{ execute-keys '<a-?>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>' }

define-command switch-number-line -params .. %{
  try %{ remove-highlighter window/number_lines }
  add-highlighter window/number_lines number-lines %arg{@}
}

map global goto '0' 'h' -docstring 'to line start'
map global goto 'J' '<esc><a-J>' -docstring 'join lines'
map global goto 'T' '<esc>s[^\d\s\W]+<ret>`<a-;>;~<space>' -docstring 'change selection to title case'
map global goto 'u' '<esc>`' -docstring 'change selection to lower case'
map global goto 'U' '<esc>~' -docstring 'change selection to upper case'
map global goto 'V' '<esc>V' -docstring 'lock view mode'

map global insert '<a-space>' ' ' -docstring 'insert space'
map global insert '<c-end>' '<end>' -docstring 'end of line'
map global insert '<c-home>' '<home>' -docstring 'start of line'
# map global insert '<c-space>'
map global insert '<c-u>' '<esc>b~/\W<ret>' -docstring 'word to uppercase'
map global insert '<s-del>' '<del>' -docstring 'delete'
map global insert '<s-ret>' '<ret><esc>O' -docstring 'insert indented block'
map global insert '<s-tab>' '<tab>' -docstring 'simple tab'
map global insert '<tab>' '<right>' -docstring 'right'

map global normal '<a-space>' '<space>' -docstring 'remove additional selections'
# map global normal '<backspace>'
# map global normal '<c-end>'
# map global normal '<c-home>'
map global normal '<c-_>' ': comment-line<ret>' -docstring 'comment/uncomment line'
map global normal '<c-h>' ': extend-previous-hump<ret>' -docstring 'extend previous word part'
map global normal '<c-l>' ': extend-next-hump<ret>' -docstring 'extend next word part'
map global normal '<c-r>' 'U' -docstring 'redo'
map global normal '<c-space>' ': buffer ' -docstring 'select buffer'
map global normal '<ret>' '<a-O>' -docstring 'add blank line above'
map global normal '<s-ret>' '<a-x><a-s>' -docstring 'split selection into lines'
map global normal '<s-tab>' ': buffer-previous<ret>' -docstring 'previous buffer'
map global normal '<space>' ';' -docstring 'collapse selection'
map global normal '<tab>' ': buffer-next<ret>' -docstring 'next buffer'
map global normal '`' 'z' -docstring 'restore selection from register'
map global normal '!' '!date' -docstring 'insert external command'
map global normal '~' '<a-`>' -docstring 'swap case'
map global normal '@' 'q' -docstring 'play macro'
map global normal '#' '<a-s>i<c-r>#<esc>;' -docstring 'enumerate selections'
map global normal '$' '<a-L>' -docstring 'select to line end'
map global normal '%' 'm' -docstring 'select to matching pair'
map global normal '^' 'Gi' -docstring 'select to line start'
map global normal '*' '<a-i>w*' -docstring 'find word under cursor'
map global normal '<minus>' '<a-space>' -docstring 'remove main selection'
map global normal '=' 'K<a-J>c<ret><esc>' -docstring 're-align lines'
map global normal '{' '{p' -docstring 'extend to paragraph start'
map global normal '}' '}p' -docstring 'extend to paragraph end'
map global normal ';' 'L<a-.>' -docstring 'repeat last find'
map global normal "'" '<a-)>' -docstring 'rotate contents right'
map global normal '|' '<a-x>|sort' -docstring 'pipe and replace with output'
map global normal 'a' 'li' -docstring 'append after cursor'
map global normal 'B' '<a-B>' -docstring 'select to WORD start'
map global normal 'C' 'Glc' -docstring 'change to line end'
map global normal 'D' 'Gld' -docstring 'delete to line end'
map global normal 'E' '<a-E>' -docstring 'select to WORD end'
map global normal 'f' 'F' -docstring 'select to find character forwards'
map global normal 'F' '<a-F>' -docstring 'select to find character backwards'
map global normal 'g' 'G' -docstring 'select to begin of object'
map global normal 'G' 'Ge' -docstring 'select to end of buffer'
map global normal 'm' 'Z' -docstring 'save selection to register'
map global normal 'M' '<a-Z>' -docstring 'append selection to register'
map global normal 'n' 'n' -docstring 'select to find next match'
map global normal 'N' '<a-n>' -docstring 'select to previous next match'
map global normal 'q' 'Q' -docstring 'start macro recording'
map global normal 'Q' '<a-C>' -docstring 'add selection above'
map global normal 'R' 'R<a-;>;' -docstring 'replace selection with register'
map global normal 't' 'T' -docstring 'select to find character forwards'
map global normal 'T' '<a-T>' -docstring 'select to find character backwards'
map global normal "U" '<a-;>' -docstring 'swap cursor and anchor'
map global normal 'V' '<a-x>' -docstring 'extend selection to full lines'
map global normal 'W' '<a-W>' -docstring 'select to next WORD start'
map global normal 'x' '<a-K>' -docstring 'exclude (keep not matching)'
map global normal 'X' '<a-k>' -docstring 'keep matching'
map global normal 'y' 'y<a-;>;' -docstring 'yank'
map global normal 'Y' 'Gly<a-;>;' -docstring 'yank to line end'
map global normal 'z' 'v' -docstring 'view mode'
map global normal 'Z' 'C' -docstring 'add selection below'

map global object 'a' '<esc>%' -docstring 'entire buffer'
map global object 'W' '<a-w>' -docstring 'WORD'

map global user '<minus>' '<esc><a-x>ypj<a-x>_r-<a-h>' -docstring 'underline string with -'
map global user '=' '<esc><a-x>ypj<a-x>_r=<a-h>' -docstring 'underline string with ='
map global user "'" '<esc><a-(>' -docstring 'rotate contents left'
map global user ',' '<esc>;<space>' -docstring 'clear all'

map global view 'a' '<esc><a-a>' -docstring '<a-a>'
map global view 'i' '<esc><a-i>' -docstring '<a-i>'

set-option global indentwidth 2
set-option global tabstop 2

colorscheme tomorrow-night
