add-highlighter global/ number-lines

hook global InsertChar \' %{ exec \'<left> }
hook global InsertChar \" %{ exec \"<left> }
hook global InsertChar \( %{ exec )<left> }
hook global InsertChar \[ %{ exec ]<left> }
hook global InsertChar \{ %[ exec }<left> ]

hook global InsertCompletionShow .* %{
  try %{
    execute-keys -draft 'h<a-K>\h<ret>'
    map window insert <a-^> <c-o> -docstring 'toggle autocomplete for this session'
    map window insert <s-tab> <c-p> -docstring 'previous suggestion'
    map window insert <tab> <c-n> -docstring 'next suggestion'
    hook -once -always window InsertCompletionHide .* %{
      unmap window insert <a-^> <c-o>
      unmap window insert <s-tab> <c-p>
      unmap window insert <tab> <c-n>
    }
  }
}

hook global NormalKey 0 'switch-number-line -relative'
hook global NormalKey \D.* 'switch-number-line'

hook global WinSetOption filetype=css %{ map buffer normal '<c-_>' '<a-x>: comment-block<ret>' -docstring 'comment/uncomment block' }
hook global WinSetOption filetype=go %{
  set-option buffer formatcmd gofmt
  set-option buffer indentwidth 0
  set-option buffer tabstop 4
}
hook global WinSetOption filetype=html %{
  hook buffer InsertChar < %{ exec ><left> }
  map buffer insert '<a-{>' '}<backspace><esc><a-b>"x\c<lt><c-r>x<gt><lt>/<c-r>x<gt><esc><a-f><lt>;i' -docstring 'html tag from previous word'
  map buffer normal '<a-#>' '<a-x>: comment-block<ret>' -docstring 'comment/uncomment block'
}
hook global WinSetOption filetype=javascript %{ hook buffer InsertChar ` %{ exec `<left> } }
hook global WinSetOption filetype=python %{
  set-option buffer indentwidth 4
  set-option buffer tabstop 4
}
hook global WinSetOption filetype=ruby %{
  hook buffer InsertChar ` %{ exec `<left> }
  map buffer insert '<s-ret>' '<ret>' -docstring 'insert indented block '
}

define-command -hidden extend-next-hump %{ execute-keys '?[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>' }
define-command -hidden extend-previous-hump %{ execute-keys '<a-?>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>' }

define-command switch-number-line -params .. %{
  try %{ remove-highlighter window/number_lines }
  add-highlighter window/number_lines number-lines %arg{@}
}

map global goto '0' 'h' -docstring 'to line start'
map global goto 'J' '<esc><a-J>' -docstring 'join lines'
map global goto 'V' '<esc>V' -docstring 'lock view mode'

map global insert '<a-^>' ' ' -docstring 'insert space'
map global insert '<a-b>' '' -docstring 'ignore alt b'
map global insert '<a-c-t>' '<esc>b;~/\W<ret>' -docstring 'word to titlecase'
map global insert '<a-u>' '<esc>b~/\W<ret>i' -docstring 'word to uppercase'
map global insert '<a-y>' '<esc>!wl-paste -n<ret>i' -docstring 'paste from system keyboard'
# map global insert '<a-y>' '<esc>!pbpaste<ret>i' -docstring 'paste from system keyboard'
map global insert '<a-.>' '<c-r>"' -docstring 'paste default register'
map global insert '<c-^>' '<esc>\i' -docstring 'insert without hooks'
map global insert '<c-space>' '<esc><a-?>\w|^|\]|\}|\)<ret>Li<space><esc><a-;>;i<space>' -docstring 'space around operator'
map global insert '<s-del>' '<del>' -docstring 'delete character right'
map global insert '<s-ret>' '<ret><esc>O' -docstring 'insert indented block'
# map global insert '<s-tab>' '<esc>: bn<ret>' -docstring 'next buffer'
map global insert '<s-tab>' '<esc>K<a-&><a-;>;i' -docstring 'copy indent from above'

map global normal '<a-#>' ': comment-line<ret>' -docstring 'comment/uncomment line'
# map global normal '<a-^>'
# map global normal '<a-.>'
map global normal '<a-b>' '' -docstring 'ignore alt b'
map global normal '<a-c-t>' 's[^\d\s\W]+<ret>`<a-;>;~<space>' -docstring 'change selection to title case'
map global normal '<a-d>' '<a-|> wl-copy > /dev/null 2>&1 <ret><space>;' -docstring 'copy to system clipboard'
# map global normal '<a-d>' '<a-|> pbcopy <ret><space>;' -docstring 'copy to system clipboard'
map global normal '<a-u>' '~' -docstring 'change selection to upper case'
map global normal '<backspace>' '<space>' -docstring 'remove additional selections'
map global normal '<c-space>' '<a-s><a-h>;' -docstring 'select first column'
map global normal '<c-l>' '`' -docstring 'change selection to lower case'
map global normal '<c-r>' 'U' -docstring 'redo'
map global normal '<s-del>' '<a-space>' -docstring 'remove primary selection'
map global normal '<s-ret>' '<a-O>' -docstring 'add blank line above'
map global normal '<s-tab>' ': bn<ret>' -docstring 'next buffer'
map global normal '<left>' 'H' -docstring 'select character left'
map global normal '<right>' 'L' -docstring 'select character right'
map global normal '<up>' 'K' -docstring 'select line up'
map global normal '<down>' 'J' -docstring 'select line down'
map global normal '<a-{>' ': buffer ' -docstring 'select buffer'
map global normal '<space>' ';' -docstring 'collapse selection'
map global normal '`' 'z' -docstring 'restore selection from register'
map global normal '!' '!date' -docstring 'insert external command'
map global normal '~' '<a-`>' -docstring 'swap case'
map global normal '@' 'q' -docstring 'play macro'
map global normal '#' '<a-*>' -docstring 'set search pattern'
map global normal '$' '<a-)>' -docstring 'rotate contents right'
map global normal '%' 'm' -docstring 'select to matching pair'
map global normal '^' '<a-(>' -docstring 'rotate contents left'
map global normal '*' '<a-i>w*' -docstring 'find word under cursor'
map global normal '=' 'K<a-J>c<ret><esc>' -docstring 're-align lines'
map global normal '{' '{p' -docstring 'extend to paragraph start'
map global normal '}' '}p' -docstring 'extend to paragraph end'
map global normal ';' 'L<a-.>' -docstring 'repeat last find'
map global normal "'" '\' -docstring 'disable hooks'
map global normal '|' '<a-x>|sort' -docstring 'pipe and replace with output'
map global normal 'a' 'li' -docstring 'append after cursor'
map global normal 'B' '<a-B>' -docstring 'select to WORD start'
map global normal "C" '<a-*><a-x>s<ret>' -docstring 'all occurrencies on current line'
map global normal 'D' 'N' -docstring 'select next match'
map global normal 'E' '<a-E>' -docstring 'select to WORD end'
map global normal 'f' 'F' -docstring 'select to find character forwards'
map global normal 'F' '<a-F>' -docstring 'select to find character backwards'
map global normal 'g' 'G' -docstring 'select to begin of object'
map global normal 'G' 'Ge' -docstring 'select to end of buffer'
map global normal 'H' ': extend-previous-hump<ret>' -docstring 'extend previous word part'
map global normal 'J' '<C>' -docstring 'add selection below'
map global normal 'K' '<a-C>' -docstring 'add selection above'
map global normal 'L' ': extend-next-hump<ret>' -docstring 'extend next word part'
map global normal 'm' 'Z' -docstring 'save selection to register'
map global normal 'M' '<a-Z>' -docstring 'append selection to register'
map global normal 'N' '<a-n>' -docstring 'select to previous next match'
map global normal 'q' 'Q' -docstring 'start macro recording'
# map global normal 'Q'
map global normal 't' 'T' -docstring 'select to find character forwards'
map global normal 'T' '<a-T>' -docstring 'select to find character backwards'
map global normal 'U' '<a-N>' -docstring 'select previous match'
map global normal 'V' '<a-_><a-x>' -docstring 'extend selection to full lines'
map global normal 'W' '<a-W>' -docstring 'select to next WORD start'
map global normal 'x' '<a-K>' -docstring 'exclude (keep not matching)'
map global normal 'X' '<a-k>' -docstring 'keep matching'
map global normal 'y' 'y<a-;>;' -docstring 'yank'
# map global normal 'Y'
map global normal 'z' 'v' -docstring 'view mode'

map global object 'a' '<esc>%' -docstring 'entire buffer'
map global object 'W' '<a-w>' -docstring 'WORD'

map global user "#" '<esc><a-s>i<c-r>#<esc>;i' -docstring 'enumerate selections'
map global user '<minus>' '<esc><a-x>ypj<a-x>_r-<a-h>' -docstring 'underline line with -'
map global user '_' '<esc><a-_>' -docstring 'merge contiguos selections'
map global user '=' '<esc><a-x>ypj<a-x>_r=<a-h>' -docstring 'underline line with ='
map global user '+' '<esc><a-+>' -docstring 'merge overlapping selections'
map global user ':' '<esc><a-:>' -docstring 'ensure cursor after anchor'
map global user ',' '<esc><a-;>' -docstring 'swap cursor'
map global user 'f' '<esc>: format<ret>' -docstring 'format buffer'
map global user 'p' '<esc><a-p>' -docstring 'paste all'
map global user 'P' '<esc><a-P>' -docstring 'paste all before'
map global user 'R' '<esc><a-R>' -docstring 'replace all'

map global view 'a' '<esc><a-a>' -docstring '<a-a>'
map global view 'd' '<esc><a-d>' -docstring 'delete without yanking'
map global view 'e' '<esc><a-S>' -docstring 'select selection ends'
map global view 'i' '<esc><a-i>' -docstring '<a-i>'

set-option global indentwidth 2
set-option global tabstop 2

colorscheme palenight
