add-highlighter global/ number-lines

hook global InsertChar \' %{ exec \'<left> }
hook global InsertChar \" %{ exec \"<left> }
hook global InsertChar \( %{ exec )<left> }
hook global InsertChar \[ %{ exec ]<left> }
hook global InsertChar \{ %[ exec }<left> ]

# hook global InsertCompletionShow .* %{
#     try %{
#         execute-keys -draft 'h<a-K>\h<ret>'
#         map window insert <s-tab> <c-p> -docstring 'previous suggestion'
#         map window insert <tab> <c-n> -docstring 'next suggestion'
#         hook -once -always window InsertCompletionHide .* %{
#             unmap window insert <s-tab> <c-p>
#             unmap window insert <tab> <c-n>
#         }
#     }
# }

hook global NormalKey 0 'switch-number-line -relative'
hook global NormalKey \D.* 'switch-number-line'

hook global WinSetOption filetype=css %{
    map buffer normal 'M' '<a-x>: comment-block<ret>' -docstring 'comment/uncomment block'
}
hook global WinSetOption filetype=go %{
    set-option buffer formatcmd gofmt
}
hook global WinSetOption filetype=html %{
    hook buffer InsertChar < %{ exec ><left> }
    map buffer normal 'M' '<a-x>: comment-block<ret>' -docstring 'comment/uncomment block'
}
hook global WinSetOption filetype=javascript %{ hook buffer InsertChar ` %{ exec `<left> } }
hook global WinSetOption filetype=ruby %{ hook buffer InsertChar ` %{ exec `<left> } }

define-command -hidden extend-next-hump %{ execute-keys '?[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>' }
define-command -hidden extend-previous-hump %{ execute-keys '<a-?>[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>' }

define-command switch-number-line -params .. %{
    try %{ remove-highlighter window/number_lines }
    add-highlighter window/number_lines number-lines %arg{@}
}

map global goto '0' 'h' -docstring 'to line start'
map global goto 'j' '<esc><a-J>' -docstring 'join lines'
map global goto 'n' '<esc>: buffer-next<ret>' -docstring 'next buffer'
map global goto 'p' '<esc>: buffer-previous<ret>' -docstring 'previous buffer'
map global goto 'r' '`' -docstring 'change selection to lower case'
map global goto 'u' '~' -docstring 'change selection to upper case'
map global goto 'y' 's[^\d\s\W]+<ret>`<a-;>;~<space>' -docstring 'change selection to title case'

declare-user-mode insertion
map global insertion ';' '<esc>A' -docstring 'end of line'
map global insertion '/' '<esc><a-b>"x\c<lt><c-r>x<gt><lt>/<c-r>x<gt><esc><a-f><lt>;i' -docstring 'html tag from previous word'
map global insertion 'h' '<esc>hi' -docstring 'move left'
map global insertion 'i' '<esc>b;~/\W<ret>i' -docstring 'word to titlecase'
map global insertion 'j' '<esc>ji' -docstring 'move down'
map global insertion 'k' '<esc>ki' -docstring 'move up'
map global insertion 'l' '<esc>li' -docstring 'move right'
map global insertion 'o' '<esc>i<ret><esc>O' -docstring 'insert indented block'
map global insertion 'p' '<esc>Pi' -docstring 'paste default register'
map global insertion 'u' '<esc>b~/\W<ret>i' -docstring 'word to uppercase'
map global insertion 'v' '<esc>!pbpaste<ret>i' -docstring 'paste from system keyboard'
map global insertion 'V' '<esc>!wl-paste -n<ret>i' -docstring 'paste from system keyboard'
map global insertion '<right>' '<esc>' -docstring 'exit mode'
map global insertion '<space>' '<esc><a-?>\w|^|\]|\}|\)<ret>Li<space><esc><a-;>;i<space>' -docstring 'space around operator'
map global insertion '<tab>' '<esc>i<tab>' -docstring 'insert tab'

map global insert '<c-^>' '<esc>\i' -docstring 'insert without hooks'
# map global insert '<ret>' '<esc>' -docstring 'exit insert mode'
map global insert '<right>' '<esc>: enter-user-mode insertion<ret>' -docstring 'enter insertion mode'
# map global insert '<s-right>' '<c-o>' -docstring 'toggle autocomplete'
map global insert <tab> <c-n> -docstring 'next suggestion'
map global insert <s-tab> <c-p> -docstring 'previous suggestion'

map global normal '<backspace>' '<space>' -docstring 'remove other selections'
map global normal '<c-space>' '<a-s><a-h>;' -docstring 'select first column'
map global normal '<c-a>' '%' -docstring 'select all'
map global normal '<c-b>' ': extend-previous-hump<ret>' -docstring 'extend previous word part'
map global normal '<c-e>' ': extend-next-hump<ret>' -docstring 'extend next word part'
map global normal '<c-r>' 'U' -docstring 'redo'
map global normal '<c-s>' '<a-N>' -docstring 'select previous match'
map global normal '<ret>' ';' -docstring 'collapse selection'
map global normal '<right>' '<esc><a-;>' -docstring 'swap cursor'
map global normal '<s-left>' '<a-space>' -docstring 'remove primary selection'
map global normal '<s-right>' '<esc><a-:>' -docstring 'ensure cursor after anchor'
map global normal '<s-tab>' '<c-o>' -docstring 'jump backwards'
# map global normal '<s-tab>' ': buffer ' -docstring 'select buffer'
map global normal '`' 'z' -docstring 'restore selection from register'
map global normal '!' '!date' -docstring 'insert external command'
map global normal '~' '<a-`>' -docstring 'swap case'
map global normal '@' 'q' -docstring 'play macro'
map global normal '#' '<a-*>' -docstring 'set search pattern'
map global normal '$' '<a-l>' -docstring 'go to end of line'
map global normal '%' 'm' -docstring 'select to matching pair'
map global normal '^' '<a-h>' -docstring 'go to start of line'
map global normal '*' '<a-i>w*' -docstring 'find word under cursor'
map global normal '=' 'K<a-J>c<ret><esc>' -docstring 're-align lines'
map global normal '{' '{p' -docstring 'extend to paragraph start'
map global normal '}' '}p' -docstring 'extend to paragraph end'
map global normal ';' 'L<a-.>' -docstring 'repeat last find'
map global normal "'" '\' -docstring 'disable hooks'
map global normal '|' '<a-x>|sort' -docstring 'pipe and replace with output'
map global normal 'a' 'li' -docstring 'append after cursor'
map global normal 'B' '<a-B>' -docstring 'select to WORD start'
map global normal 'D' 'N' -docstring 'select next match'
map global normal 'E' '<a-E>' -docstring 'select to WORD end'
map global normal 'f' 'F' -docstring 'select to find character forwards'
map global normal 'F' '<a-F>' -docstring 'select to find character backwards'
map global normal 'g' 'G' -docstring 'select to begin of object'
map global normal 'G' 'Ge' -docstring 'select to end of buffer'
map global normal 'm' 'Z' -docstring 'save selection to register'
map global normal 'M' ': comment-line<ret>' -docstring 'comment/uncomment line'
# map global normal 'N' '<a-n>' -docstring 'select to previous next match'
map global normal 'q' 'Q' -docstring 'start macro recording'
map global normal 'Q' '<a-(>' -docstring 'rotate contents left'
map global normal 't' 'T' -docstring 'select to find character forwards'
map global normal 'T' '<a-T>' -docstring 'select to find character backwards'
map global normal 'V' '<a-_><a-x>' -docstring 'extend selection to full lines'
map global normal 'W' '<a-W>' -docstring 'select to next WORD start'
map global normal 'x' '<a-K>' -docstring 'exclude (keep not matching)'
map global normal 'X' '<a-k>' -docstring 'keep matching'
map global normal 'y' 'y<a-;>;' -docstring 'yank'
map global normal 'Y' '<a-)>' -docstring 'rotate contents right'
map global normal 'z' '<a-Z>' -docstring 'append selection to register'
map global normal 'Z' '<a-C>' -docstring 'add selection above'

map global object 'W' '<a-w>' -docstring 'WORD'

map global user "c" '<a-*><a-x>s<ret>' -docstring 'all occurrencies on current line'
map global user "#" '<esc><a-s>i<c-r>#<esc>;i' -docstring 'enumerate selections'
map global user '<minus>' '<esc><a-x>ypj<a-x>_r-<a-h>' -docstring 'underline line with -'
map global user '_' '<esc><a-_>' -docstring 'merge contiguos selections'
map global user '=' '<esc><a-x>ypj<a-x>_r=<a-h>' -docstring 'underline line with ='
map global user '+' '<esc><a-+>' -docstring 'merge overlapping selections'
map global user 'f' '<esc>: format<ret>' -docstring 'format buffer'
map global user 'l' '<a-|> wl-copy > /dev/null 2>&1 <ret><space>;' -docstring 'copy to system clipboard'
map global user 'm' '<a-|> pbcopy <ret><space>;' -docstring 'copy to system clipboard'
map global user 'p' '<esc><a-p>' -docstring 'paste all'
map global user 'P' '<esc><a-P>' -docstring 'paste all before'
map global user 'R' '<esc><a-R>' -docstring 'replace all'

map global view 'a' '<esc><a-a>' -docstring '<a-a>'
map global view 'd' '<esc><a-d>' -docstring 'delete without yanking'
map global view 'e' '<esc><a-S>' -docstring 'select selection ends'
map global view 'i' '<esc><a-i>' -docstring '<a-i>'
map global view 'V' '<esc>V' -docstring 'lock view mode'
