#!/usr/bin/env zsh

if [[ -n $ZSH_VERSION ]]; then
  DSHELL=ZSH
  setopt ksh_arrays
elif [[ -n $BASH_VERSION ]]; then
  DSHELL=BASH
else
  DSHELL=MISC
fi

PHEADER() {
  local args=${*}
  if [[ $DSHELL == ZSH ]]; then
    local str=${(U)args}
  elif [[ $DSHELL == BASH ]]; then
    local str=${args^^}
  else
    local str=$(echo -n ${args} | tr '[:lower:]' '[:upper:]')
  fi
  local termwidth=$(tput cols)
  local padding=$(printf '%s' '===================================================================================================================================================================')
  printf '%*.*s %s %*.*s\n' 0 "$(((termwidth-2-${#str})/2))" "${padding}" "${str}" 0 "$(((termwidth-1-${#str})/2))" "${padding}"
}

if [[ -p /dev/stdin ]]; then
  while IFS= read line; do
    PHEADER $line
  done
else
  if [[ $# > 0 ]]; then
    PHEADER $*
  else
    echo 'Usage: phd <text>'
    echo '       Text can also be piped'
  fi
fi
