#!/usr/bin/env python3

import argparse
import fileinput
import shutil

def filter_line(args, line):
  if args.find and (args.find not in line): return False
  if args.Find and (args.Find.lower() not in line.lower()): return False
  if args.exclude and (args.exclude in line): return False
  if args.Xclude and (args.Xclude.lower() in line.lower()): return False
  return True

def process_line(args, line, num):
  l = line
  if args.enumerate: l = f'{num + args.Number - 1}{args.Separator}{l}'
  if args.convert:
    if 'trim' in args.convert: l = l.strip()
    if 'trimleft' in args.convert: l = l.lstrip()
    if 'trimright' in args.convert: l = l.rstrip()

    if 'lower' in args.convert: l = l.lower()
    if 'sentence' in args.convert: l = l.capitalize()
    if 'swapcase' in args.convert: l = l.swapcase()
    if 'title' in args.convert: l = l.title()
    if 'upper' in args.convert: l = l.upper()

    if 'center' in args.convert: l = l.center(args.Number, args.Separator)
    if 'left' in args.convert: l = l.ljust(args.Number, args.Separator)
    if 'right' in args.convert: l = l.rjust(args.Number, args.Separator)
  return l

if __name__ == '__main__':
  parser = argparse.ArgumentParser()
  parser.add_argument('-c', '--convert', choices = ['center', 'left', 'right',
    'lower', 'sentence', 'swapcase', 'title', 'upper',
    'trim', 'trimleft', 'trimright'], nargs = '*', help = 'Convert with specified method')
  parser.add_argument('-e', '--enumerate', action='store_true', help = 'Enumerate using Separator and starting with Number')
  parser.add_argument('-n', '--number', type = int, help = 'Count of lines to process')
  parser.add_argument('-N', '--Number', type = int, help = 'Option number for {center, enumerate, left, right}')
  parser.add_argument('-f', '--find', help = 'Text to search, no regexp, case insensitive')
  parser.add_argument('-F', '--Find', help = 'Text to search, no regexp, case sensitive')
  parser.add_argument('-S', '--Separator', help = 'Option separator for {center, enumerate, left, right}')
  parser.add_argument('-x', '--exclude', help = 'Text to exclude, no regexp, case insensitive')
  parser.add_argument('-X', '--Xclude', help = 'Text to exclude, no regexp, case sensitive')
  parser.add_argument('input_files', metavar = 'FILE', nargs = '*', help = 'Additional input file(s)')
  args = parser.parse_args()

  if args.Number == None:
    if args.enumerate:
      args.Number = 1
    elif args.convert:
      args.Number = shutil.get_terminal_size()[0]

  if args.Separator == None:
    if args.enumerate:
      args.Separator = '.'
    elif args.convert:
      args.Separator = ' '

  if args.enumerate and args.convert and ('center' in args.convert or 'left' in args.convert or 'right' in args.convert):
    print('Conflicting operations, aborting')
    exit(1)

  num = 0
  for count, line in enumerate(fileinput.input(files = args.input_files), start = 1):
    if args.number and (count > args.number): break
    if not filter_line(args, line): continue
    num += 1
    o = process_line(args, line, num)
    print(o, end='')
