mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  startup_mode: Maximized
key_bindings:
  - { key: Escape,    mods: Shift,        chars: "\x1b[F" } # (Caps) End
  - { key: Back,   mods: Shift,   chars: "\x1b[H" } # Home
  - { key: Return, mods: Shift,   chars: "\x1b[6~" } # PageDown
  - { key: Space,  mods: Shift,   chars: "\x1b[5~" } # PageUp
