mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  startup_mode: Maximized
key_bindings:
  - { key: Back, mods: Shift  , chars: "\x0b"     } # Ctrl-K
  - { key: Back, mods: Control, chars: "\x1b\x7f" } # Alt-Backspace
