mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  startup_mode: Maximized
key_bindings:
  - { key: Escape,    mods: Shift,        chars: "\x1bp" } # (Caps) Alt-p
  - { key: Back,   mods: Shift,   chars: "\x1bb" } # Alt-b
  - { key: Return, mods: Shift,   chars: "\x1bn" } # Alt-n
  - { key: Space,  mods: Shift,   chars: "\x1bf" } # Alt-f
