[[keyboard.bindings]]
chars = "\u001B" # Escape
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F" # Alt-Backspace
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B-\u001Bu" # Alt-U
key = "Return"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B-\u001Bl" # Alt-L
key = "Return"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
startup_mode = "Maximized"
