mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  startup_mode: Maximized
key_bindings:
  - { key: 58  , mods: None , chars: "\x1b"     } # Escape
  - { key: Back, mods: Shift, chars: "\x1b\x7f" } # Alt Backspace
