[[keyboard.bindings]]
action = "ToggleViMode"
key = 58
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = 58
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B-\u001Bu"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B-\u001Bl"
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "Space"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
startup_mode = "Maximized"
