[[keyboard.bindings]]
chars = "\u000D" # Enter
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B" # Escape
key = "Return"
mods = "None"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F" # Alt-Backspace
key = "Back"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B-\u001Bu" # Alt-U
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B-\u001Bl" # Alt-L
key = "Tab"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u000F" # Control-O
key = "Space"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
startup_mode = "Maximized"
