mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  startup_mode: Maximized
key_bindings:
  - { key: 58  , mods: None   , chars: "\x1b-"    } # Alt-minus
  - { key: 58  , mods: Shift  , chars: "\x1b^"    } # Alt-^
  - { key: Back, mods: Shift  , chars: "\x0b"     } # Ctrl-K
  - { key: Back, mods: Control, chars: "\x1b\x7f" } # Alt-Backspace
