mouse:
  hide_when_typing: true
scrolling:
  history: 10000
window:
  decorations: none
  startup_mode: Maximized
key_bindings:
  - { key: Escape,    mods: Shift,        chars: "\x15" } # (Caps) Ctrl-u
  - { key: Back,   mods: Shift,   chars: "\x10" } # Ctrl-p
  - { key: Return, mods: Shift,   chars: "\x0e" } # Ctrl-n
  - { key: Space,  mods: Shift,   chars: "\x0b" } # Ctrl-k
