[[keyboard.bindings]]
chars = "`"
key = "ä"
mods = "None"

[[keyboard.bindings]]
chars = "~"
key = "ä"
mods = "Shift"

[[keyboard.bindings]]
chars = "="
key = "ß"
mods = "None"

[[keyboard.bindings]]
chars = "["
key = "ü"
mods = "None"

[[keyboard.bindings]]
chars = "{"
key = "ü"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B" # Escape
key = "ü"
mods = "Control"

[[keyboard.bindings]]
chars = "]"
key = "ö"
mods = "None"

[[keyboard.bindings]]
chars = "}"
key = "ö"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001D" # Control-]
key = "ö"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[F\u000D" # End, Enter
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[C" # Right
key = ";"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[F" # End
key = "'"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control|Shift"

# [[keyboard.bindings]]
# chars = "\u001B[3~" # Delete
# key = "Return"
# mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B\u007F" # Alt-Backspace
key = "Back"
mods = "Control"

# [[keyboard.bindings]]
# chars = "\u001B-\u001Bl" # Alt-L
# key = "Return"
# mods = "Control|Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[window]
startup_mode = "Maximized"
