import:
  - ~/Published/configs/alacritty/dark.yml
  - ~/Published/configs/alacritty/common.yml
font:
  size: 13
  normal:
    family: JetBrainsMono
window:
  decorations: None
key_bindings:
  - { key: Back  , mods: None     , chars: "\x1b[1;5D" } # Ctrl Left
  - { key: Space , mods: None     , chars: "\x1b[1;5C" } # Ctrl Right
  - { key: Return, mods: None     , chars: "\x1b[1;5F" } # Ctrl End
  - { key: Tab   , mods: None     , chars: "\x1b[1;5H" } # Ctrl Home
  - { key: Back  , mods: Alt|Shift, chars: "\x1b[B"    } # Down
  - { key: Space , mods: Alt|Shift, chars: "\x1b[A"    } # Up
  - { key: Return, mods: Alt|Shift, chars: "\x1b[5~"   } # PageUp
  - { key: Tab   , mods: Alt|Shift, chars: "\x1b[6~"   } # PageDown
shell:
  program: /home/yerlaser/.cargo/bin/nu
env:
  THEME: Dark
  BAT_THEME: ''
  _ZO_DATA_DIR: /tmp/zoxideDark
