import:
  - ~/Published/configs/alacritty/dark.yml
  - ~/Published/configs/alacritty/common.yml
font:
  size: 13
  normal:
    family: JetBrainsMono
key_bindings:
  - { key: Up      , mods: None , chars: "\x1b[1;3A" } # Alt Up
  - { key: Down    , mods: None , chars: "\x1b"      } # Escape
  - { key: Right   , mods: None , chars: "\x1b[1;3C" } # Alt Right
  - { key: Left    , mods: None , chars: "\x1b[1;3D" } # Alt Left
  - { key: PageUp  , mods: Shift, chars: "\x1b[5;3~" } # Alt PageUp
  - { key: PageDown, mods: Shift, chars: "\x1b[6;3~" } # Alt PageDown
  - { key: End     , mods: Shift, chars: "\x1b[1;3F" } # Alt End
  - { key: Home    , mods: Shift, chars: "\x1b[1;3H" } # Alt Home
shell:
  program: /home/yerlaser/.cargo/bin/nu
env:
  THEME: Dark
  BAT_THEME: ''
  _ZO_DATA_DIR: /tmp/zoxideDark
