import = ["~/Published/configs/alacritty/dark.toml", "~/Published/configs/alacritty/common.toml"]

[env]
BAT_THEME = ""
THEME = "Dark"
_ZO_DATA_DIR = "/tmp/zoxideDark"

[font]
size = 13

[font.normal]
family = "JetBrainsMono"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Back"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u000B"
key = "Back"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Back"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Return"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u000F"
key = "Return"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001B"
key = "Space"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Space"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Tab"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Tab"
mods = "None"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Tab"
mods = "Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Tab"
mods = "Shift"
mode = "Vi"

[shell]
program = "/LOCAL/apps/cargo/bin/nu"

[window]
decorations = "None"
