import = ["~/Published/configs/alacritty/dark.toml", "~/Published/configs/alacritty/common.toml"]

[env]
THEME = "Dark"

[font]
size = 13

[font.normal]
family = "JetBrainsMono"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "End"
mods = "None"

[[keyboard.bindings]]
action = "ReceiveChar"
key = "Home"
mods = "Shift"

[shell]
program = "/LOCAL/apps/cargo/bin/nu"

[window]
decorations = "None"
