import:
  - ~/Published/configs/alacritty/dark.yml
  - ~/Published/configs/alacritty/common.yml
font:
  size: 13
  normal:
    family: JetBrainsMono
window:
  decorations: None
key_bindings:
  - { key: Left  , mods: None     , chars: "\x1b[1;5D" } # Ctrl Left
  - { key: Right , mods: None     , chars: "\x1b[1;5C" } # Ctrl Right
  - { key: End   , mods: None     , chars: "\x1b[1;5F" } # Ctrl End
  - { key: Home  , mods: None     , chars: "\x1b[1;5H" } # Ctrl Home
shell:
  program: /home/yerlaser/.cargo/bin/nu
env:
  THEME: Dark
  BAT_THEME: ''
  _ZO_DATA_DIR: /tmp/zoxideDark
