import:
  - ~/Published/configs/alacritty/dark.yml
  - ~/Published/configs/alacritty/common.yml
font:
  size: 13
  normal:
    family: JetBrainsMono
key_bindings:
  - { key: Pause, mods: None, chars: "\x1b[1;6D" } # Control Shift Left
  - { key: NumpadEnter, mods: None, chars: "\x1b[1;6C" } # Control Shift Right
  - { key: Pause, mods: Shift, chars: "\x1b[1;6H" } # Control Shift Home
  - { key: NumpadEnter, mods: Shift, chars: "\x1b[1;6F" } # Control Shift End
  - { key: Escape, mods: Shift, chars: "\x1b[5;6~" } # Control Shift PageUp
shell:
  program: /home/yerlan/.cargo/bin/nu 
  args:
    - --config ~/Published/configs/nushell/config.nu
    - --env-config ~/Published/configs/nushell/env.nu
env:
  THEME: Dark
  BAT_THEME: ''
  _ZO_DATA_DIR: /tmp/zoxideDark
