import:
  - ~/Published/configs/alacritty/dark.yml
  - ~/Published/configs/alacritty/common.yml
font:
  size: 13
  normal:
    family: JetBrainsMono
window:
  decorations: None
shell:
  program: /home/yerlaser/.cargo/bin/nu
env:
  THEME: Dark
  BAT_THEME: ''
  _ZO_DATA_DIR: /tmp/zoxideDark
