import:
  - ~/Published/configs/alacritty/dark.yml
  - ~/Published/configs/alacritty/common.yml
font:
  size: 13
  normal:
    family: JetBrainsMono
key_bindings:
  - { key: 26, mods: Shift, chars: "{"     }
  - { key: 27, mods: Shift, chars: "}"     }
  - { key: 43, mods: Shift, chars: "|"     }
  - { key: 51, mods: Shift, chars: "<"     }
  - { key: 52, mods: Shift, chars: ">"     }
  - { key: U,  mods: Super, chars: "\x1bu" }
shell:
  program: /home/yerlan/.cargo/bin/nu 
  args:
    - --config ~/Published/configs/nushell/config.nu
    - --env-config ~/Published/configs/nushell/env.nu
env:
  THEME: Dark
  BAT_THEME: ''
  _ZO_DATA_DIR: /tmp/zoxideDark
