import:
  - ~/Published/configs/alacritty/common.yml
font:
  size: 18
  normal:
    family: Monaco
key_bindings:
  - { key: Back, mods: Option, chars: "\x1b[1;6D" } # Control Shift Left
  - { key: Return, mods: Option, chars: "\x1b[1;6C" } # Control Shift Right
  - { key: Space, mods: Option, chars: "\x1b" } # Escape
  - { key: Back, mods: Option|Shift, chars: "\x1b[1;6H" } # Control Shift Home
  - { key: Return, mods: Option|Shift, chars: "\x1b[1;6F" } # Control Shift End
  - { key: Space, mods: Option|Shift, chars: "\x1b[5;6~" } # Control Shift PageUp
  - { key: T, mods: Command, command: {program: "/Users/yerlan/Applications/Alacritty.app/Contents/MacOS/alacritty", args: ["--config-file", "/Users/yerlan/Published/configs/alacritty/macosDark.yml"]}   }
shell:
  program: /Users/yerlan/.cargo/bin/nu
  args:
    - --config ~/Published/configs/nushell/config.nu
    - --env-config ~/Published/configs/nushell/env.nu
