import = ["~/Published/configs/alacritty/common.toml"]

[font]
size = 18

[font.normal]
family = "Monaco"

# [[keyboard.bindings]]
# chars = "\u001B[D" # Left
# key = "Back"
# mods = "Option"

# [[keyboard.bindings]]
# chars = "\u001B[1;2H" # Shift-Home
# key = "Back"
# mods = "Option|Shift"

# [[keyboard.bindings]]
# chars = "\u001B[C" # Right
# key = "Return"
# mods = "Option"

# [[keyboard.bindings]]
# chars = "\u001B[1;2F" # Shift-End
# key = "Return"
# mods = "Option|Shift"

# [[keyboard.bindings]]
# chars = "\u001B[A" # Up
# key = "Space"
# mods = "Option"

# [[keyboard.bindings]]
# chars = "\u001B[5;2~" # Shift-PageUp
# key = "Space"
# mods = "Option|Shift"

# [[keyboard.bindings]]
# chars = "\u001B[B" # Down
# key = "Tab"
# mods = "Option"

# [[keyboard.bindings]]
# chars = "\u001B[6;2~" # Shift-PageDown
# key = "Tab"
# mods = "Option|Shift"

[shell]
program = "/Users/yerlan/.cargo/bin/nu"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
