import = ["~/Published/configs/alacritty/dark.toml", "~/Published/configs/alacritty/macos.toml"]

[env]
BAT_THEME = ""
THEME = "Dark"
_ZO_DATA_DIR = "/tmp/zoxideDark"

[[keyboard.bindings]]
key = "T"
mods = "Command"

[keyboard.bindings.command]
args = ["--config-file", "~/Published/configs/alacritty/macosLight.toml"]
program = "~/Applications/Alacritty.app/Contents/MacOS/alacritty"
