import = ["~/Published/configs/alacritty/common.toml"]

[font]
size = 18

[font.normal]
family = "Monaco"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Back"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u000B"
key = "Back"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Back"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Return"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u000F"
key = "Return"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Return"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001B"
key = "Space"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001B[A"
key = "Space"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Tab"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Tab"
mods = "Option"
mode = "Vi"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Tab"
mods = "Option|Shift"
mode = "Vi"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Tab"
mods = "Option|Shift"
mode = "Vi"

[shell]
program = "/Users/yerlan/.cargo/bin/nu"

[window]
decorations = "Buttonless"
option_as_alt = "OnlyRight"
