env:
  THEME: Light
  BAT_THEME: GitHub
import:
  - ~/Published/configs/alacritty/light.yml
  - ~/Published/configs/alacritty/macos.yml
shell:
  program: /Users/yerlan/.cargo/bin/nu
  args:
    - --config ~/Published/configs/nushell/config.nu
    - --env-config ~/Published/configs/nushell/env.nu