import = ["~/Published/configs/alacritty/dark.toml", "~/Published/configs/alacritty/macos.toml"]

[env]
THEME = "Dark"

[[keyboard.bindings]]
key = "T"
mods = "Command"

[keyboard.bindings.command]
args = ["--config-file", "/Users/yerlan/Published/configs/alacritty/macosLight.toml"]
program = "/Users/yerlan/Applications/Alacritty.app/Contents/MacOS/alacritty"
