import = ["~/Published/configs/alacritty/light.toml", "~/Published/configs/alacritty/macos.toml"]

[env]
BAT_THEME = "GitHub"
THEME = "Light"
_ZO_DATA_DIR = "/tmp/zoxideLight"

[[keyboard.bindings]]
key = "T"
mods = "Command"

[keyboard.bindings.command]
args = ["--config-file", "~/Published/configs/alacritty/macosLight.yml"]
program = "~/Applications/Alacritty.app/Contents/MacOS/alacritty"
