apiVersion: v1
kind: Pod
metadata:
  name: my-pod1
spec:
  containers:
    - name: main
      image: alpine:latest
      command: ["/bin/sh", "-c", 'printenv']
      envFrom:
        - configMapRef:
            name: some-data
