apiVersion: v1
kind: Pod
metadata:
  name: my-pod2
spec:
  containers:
    - name: main
      image: alpine:latest
      command: ["/bin/sh", "-c", 'printenv']
      env:
        - name: greeting
          valueFrom:
            configMapKeyRef:
              name: some-data
              key: greeting
